Add documentation
RealKC/Reiji pull request #1
Opened 2020-08-09 20:08 UTC by RealKC

* [x] Document public APIs
* [ ] Make docs build fine
* [ ] Add a github action to publish my docs to github pages

2020-08-17 21:53 UTC, RealKC commented
Figuring out why stuff that works locally doesn't work on CI is fun....

2020-08-17 21:57 UTC, RealKC commented
Ugh, I'll continue this tomorrow

2020-08-18 07:14 UTC, Kime78 commented on docs/symbol.rst
> +Throughout this docu ment the term ``invalid`` is used to refer to a symbol on
You accidentally put a space on the word `document`, you wrote `docu ment`

2020-08-18 07:27 UTC, Kime78 requested changes
Needs more examples, try addressing these questions: how do I call a method from a symbol, what does reiji::unique_shared_lib contain

2021-01-24 18:19 UTC, RealKC commented
Didn't really get anywhere, and I dislike some of `breathe`.

Will eventually revisit with a different approach.

2021-01-24 18:19 UTC, closed without merging